import {
  BookOpen,
  Users,
  CalendarDays,
  ArrowRight,
} from "lucide-react";
import { Link } from "react-router-dom";

export default function TeacherDashboard() {
  const cards = [
    {
      title: "Subjects",
      description: "View all available subjects.",
      icon: BookOpen,
      link: "/teacher/subjects",
      color: "bg-blue-500",
    },
    {
      title: "Teachers",
      description: "Browse the faculty directory.",
      icon: Users,
      link: "/teacher/teachers",
      color: "bg-emerald-500",
    },
    {
      title: "Timetable",
      description: "View the latest timetable.",
      link: "/teacher/runs",
      icon: CalendarDays,
      color: "bg-violet-500",
    },
  ];

  return (
    <div className="space-y-8">

      {/* ================= Welcome ================= */}

      <div className="rounded-3xl bg-gradient-to-r from-blue-600 to-indigo-600 p-8 text-white shadow-lg">

        <h1 className="text-4xl font-bold">
          Welcome Teacher 👋
        </h1>

        <p className="mt-3 text-blue-100 text-lg max-w-2xl">
          Welcome to the Schedulify Teacher Portal. Here you can
          view subjects, browse faculty information and access
          the latest timetable generated by the administrator.
        </p>

      </div>

      {/* ================= Quick Actions ================= */}

      <div>

        <h2 className="text-2xl font-bold text-slate-800 mb-5">
          Quick Actions
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">

          {cards.map((card) => {
            const Icon = card.icon;

            return (
              <Link
                key={card.title}
                to={card.link}
                className="group rounded-2xl bg-white p-6 shadow-sm border border-slate-200 hover:shadow-xl hover:-translate-y-1 transition"
              >
                <div
                  className={`h-14 w-14 rounded-2xl ${card.color} flex items-center justify-center text-white`}
                >
                  <Icon size={28} />
                </div>

                <h3 className="mt-6 text-xl font-semibold text-slate-800">
                  {card.title}
                </h3>

                <p className="mt-2 text-slate-500">
                  {card.description}
                </p>

                <div className="mt-6 flex items-center text-blue-600 font-medium">
                  Open
                  <ArrowRight
                    className="ml-2 group-hover:translate-x-1 transition"
                    size={18}
                  />
                </div>
              </Link>
            );
          })}

        </div>

      </div>

      {/* ================= Information ================= */}

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">

        <div className="rounded-2xl bg-white p-6 shadow-sm border border-slate-200">
          <h3 className="text-xl font-semibold text-slate-800">
            Teacher Portal
          </h3>

          <p className="mt-3 text-slate-600 leading-7">
            This portal provides read-only access to academic
            information. Teachers can browse subjects,
            faculty details and view the generated timetable.
          </p>
        </div>

        <div className="rounded-2xl bg-white p-6 shadow-sm border border-slate-200">
          <h3 className="text-xl font-semibold text-slate-800">
            Timetable Information
          </h3>

          <p className="mt-3 text-slate-600 leading-7">
            Timetables are generated by the administrator using
            the Timefold optimization engine. Teachers always
            view the latest published timetable.
          </p>
        </div>

      </div>

    </div>
  );
}